version: "3"

services:
  imaginary:
    image: h2non/imaginary
    network_mode: "host"
    ports:
      - "9000:9000"
    environment:
      - PORT=9000
    command: -concurrency 50 -enable-url-source

